name: Chroma Server Image

on:
  workflow_dispatch:
    inputs:
      chroma_version:
        description: 'Chroma version to use for the image'
        required: true
        default: '0.6.3'
      latest:
        description: 'Whether to use the latest tag'
        required: false
        default: 'false'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/chroma
  AWS_REGION : "eu-west-1"

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read
    packages: write

jobs:

  build:
    name: ${{ matrix.base }} Chroma Server Image
    strategy:
      fail-fast: false
      matrix:
        base: ["bookworm", "alpine"]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Chroma repository
        uses: actions/checkout@v4
        with:
          repository: chroma-core/chroma
          path: chroma
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          ref: ${{ inputs.chroma_version }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::531530523245:role/github-oidc
          role-session-name: chroma-images-oidc
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.0

      - name: Configure
        run: |
          set -e
          cp common/log_config.yaml chroma/log_config.yaml
          cp common/docker_entrypoint.sh chroma/docker_entrypoint.sh
          rm -rf chroma/chromadb/utils/embedding_functions
          cp common/embedding_functions.py chroma/chromadb/utils/embedding_functions.py
          cp common/.dockerignore chroma/.dockerignore
          cp ${{ matrix.base }}/Dockerfile.${{ matrix.base }} chroma/Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern=${{ inputs.chroma_version }}-${{ matrix.base }}
            type=raw,value=${{ inputs.chroma_version }}-${{ matrix.base }}
            type=raw,value=latest-${{ matrix.base }},enable=${{ inputs.latest == 'true' }}
            type=raw,value=latest,enable=${{ inputs.latest == 'true' && matrix.base == 'bookworm' }}
            type=sha,format=long

      - name: Build Docker image for testing
        uses: docker/build-push-action@v5
        with:
          context: ./chroma
          push: false
          load: true
          tags: local-test-image:${{ matrix.base }}

      - name: Test
        id: test
        #skip this step
        if: false
        shell: bash
        run: |
          set -e
          export FIRST_TAG="local-test-image:${{ matrix.base }}"
          export CHROMA_PORT=${{ env.CHROMA_PORT }}
          cd chroma && pip install -r requirements.txt && pip install -r requirements_dev.txt && cd ..
          bash bin/integration-test.sh ${{ env.TESTS }}
        env:
          CHROMA_PORT: 8000
          TESTS: "--ignore-glob 'chromadb/test/property/*' --ignore='chromadb/test/test_cli.py' --ignore-glob 'chromadb/test/distributed/*' --ignore='chromadb/test/auth/test_simple_rbac_authz.py' --ignore='chromadb/test/ef/' --ignore='chromadb/test/db' --ignore='chromadb/test/segment/distributed' --ignore='chromadb/test/test_logservice.py' --ignore='chromadb/test/proto' --ignore='chromadb/test/auth/'"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: local-test-image:${{ matrix.base }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Set up Docker Buildx for push
        if: success()
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Final Image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: ./chroma
          push: true
          platforms: linux/amd64 #,linux/arm64,linux/arm/v7
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get image ref
        id: image-ref
        run: |
          set -e
          FIRST_TAG="$(echo ${{ steps.meta.outputs.tags }} | head -n 1)"
          echo "image-ref=${FIRST_TAG}" >> $GITHUB_OUTPUT

      - name: Run Trivy SBOM
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.image-ref.outputs.image-ref }}
          format: 'cyclonedx'
          output: 'chroma.cdx.json'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.image-ref.outputs.image-ref }}
          format: 'cosign-vuln'
          output: 'chroma.vuln.json'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign image with a key
        run: |
          set -e
          cosign sign --key ${COSIGN_PUBLIC_KEY} --tlog-upload=false ${{ steps.image-ref.outputs.image-ref }}
          cosign attest --key ${COSIGN_PUBLIC_KEY} --type cyclonedx --predicate chroma.cdx.json --tlog-upload=false ${{ steps.image-ref.outputs.image-ref }}
          cosign attest --key ${COSIGN_PUBLIC_KEY} --type vuln --predicate chroma.vuln.json --tlog-upload=false ${{ steps.image-ref.outputs.image-ref }}
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.AWS_KMS_OSS_IMAGE_SIGNING_KEY }}
          